plugins {
    id 'com.android.application'
}

android {
    namespace 'mz.nader.hipertrofiapro'
    compileSdk 36

    defaultConfig {
        applicationId 'mz.nader.hipertrofiapro'
        minSdk 24
        targetSdk 36
        versionCode 6
        versionName '6.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.16.0'
}
